[package]
name = "wss"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {workspace = true}
serde = {workspace = true}
serde_json = {workspace = true}
redis = {workspace = true}
tokio-tungstenite = {workspace = true}
dotenv = {workspace = true}
futures-util = {workspace = true}