[workspace]
"resolver" = "3"
members = ["api"]

[workspace.dependencies]
actix-web = "4.11.0"
dotenv = "0.15.0"
derive_more = "2.0.1"
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.140"