
/*

    - ENGINE SHOULD BE STARTED IN MAIN THREAD
    - EACH ORDERBOOK SHOOULD BE STARTED IN ANOTHER THREAD
    - WHEN ENGINE STARTS IT SHOULD POLL THE ORDER QUEUE AND SEND ORDER TO RELEVANT ORDERBOOK
    - WHEN AN ORDER IS EXECUTED OR PROCESSED, THE ORDERBOOK SHOULD NOTIFY THE ENGINE
    - THE ENGINE CAN THEN PUBLISH TO THE ORDER_ID CHANNEL
*/

fn main() {
    println!("Hello, world!");
}
