[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { workspace = true } 
dotenv = { workspace = true }
derive_more = { workspace = true }
serde = { workspace = true }
